name: NuGet Release

on:
  push:
    tags:
      - 'core-v*'

jobs:
  pack-and-push:
    runs-on: ubuntu-latest

    # ✅ secrets를 env로 먼저 주입
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Restore
        run: dotnet restore src/ZenECS.Core/ZenECS.Core.csproj

      - name: Build
        run: dotnet build -c Release --no-restore src/ZenECS.Core/ZenECS.Core.csproj

      - name: Pack
        run: dotnet pack -c Release --no-build -o artifacts src/ZenECS.Core/ZenECS.Core.csproj

      - name: Verify outputs
        run: |
          ls -la artifacts
          test -n "$(ls -1 artifacts/*.nupkg 2>/dev/null)" || (echo "No .nupkg found in artifacts" && exit 2)

      # ✅ if에서는 env 컨텍스트를 사용해 비교
      - name: Push to NuGet (skip if no key)
        if: ${{ env.NUGET_API_KEY != '' }}
        run: dotnet nuget push artifacts/*.nupkg --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate

      - name: Skip NuGet push (no API key)
        if: ${{ env.NUGET_API_KEY == '' }}
        run: echo "NUGET_API_KEY not set. Skipping NuGet push."
