name: UPM Unity Adapter & Tag

on:
  workflow_dispatch:
    inputs:
      adapter_version:
        description: 'Adapter version (e.g., 1.0.0)'
        required: false

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split Adapter
        if: ${{ inputs.adapter_version != '' }}
        run: |
          git subtree split --prefix=Packages/com.zenecs.adapter.unity -b split/adapter
          git tag -f upm-adapter-${{ inputs.adapter_version }} split/adapter
          git push origin split/adapter --force
          git push origin --tags --force
